### ISSUE TITLE
Add option to pre-enable CRYPTO_PRIMITIVES and GET_BLOCK_NUM protocol features on subst_plugin

### ISSUE THREAD

**Issue by guilledk** [guilledk/leap#18]
In order for us to run our new `telos.evm` contract with the pre compiles using the 4.0.0 cdt in old block ranges, we have to pre-enable two procol features.

Aceptance Criteria:

Sync to head using this branch:
- https://github.com/telosnetwork/leap/tree/pre_enable_primitives
- https://github.com/telosnetwork/telos.evm/tree/intrinsics_replace

**Comment by pmjanus** [comment]
After extensive testing we found out this isn't required as there is no internal check on nodeos that prevents crypto primitives being called even when protocol features aren't enabled.
