### ISSUE TITLE
Make sure max tx time override works on EVM (Multicall)

### ISSUE THREAD

**Issue by rozzaswap** [guilledk/leap#28]
https://gist.github.com/guilledk/0735d3d3294c1cdc8fe71b12f9f5f7b5

**Comment by guilledk** [comment]
This test: https://github.com/telosnetwork/telos-evm-docker/blob/master/tests/test_tx_time_override.py

which uses this contract to calculate primes: https://github.com/guilledk/evm-mechanics/blob/52a989a7bba5d5088bdb3c89b2b5fd4bfbf2f47d/src/EVMMechanics.sol

if i pass `--override-max-tx-time=499` i can calculate up to 2200, if i dont i only can up to 1200

So, im gonna say its working as intenteded, and in any case something familiar with multicall's having issues should check it out.
